name = "akhil-portfolio"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[analytics_engine_datasets]]
binding = "PHOTO_ANALYTICS"
dataset = "photo_views"

[[r2_buckets]]
binding = "PORTFOLIO_BUCKET"
bucket_name = "portfolio-photos"

[vars]
GITHUB_REPO = "akhil-saxena/portfolio"
R2_PUBLIC_URL = "https://pub-2d90aedeebcf4142afe524930c3b6471.r2.dev"
